env:
  TERM: xterm-256color

window:
  #dimensions:
  #  columns: 0
  #  lines: 0
  #position:
  #  x: 0
  #  y: 0
  padding:
    x: 0
    y: 0
  # Spread additional padding evenly around the terminal content.
  #dynamic_padding: false

  # Window decorations
  # decorations: none

  # Startup Mode (changes require restart)
  # Values for `startup_mode`:
  #   - Windowed
  #   - Maximized
  #   - Fullscreen
  startup_mode: Maximized

  # Allow terminal applications to change Alacritty's window title.
  dynamic_title: true

scrolling:
  history: 10000
  multiplier: 3

font:
  normal:
    family: Fira Code
    style: Regular
  bold:
    family: Fira Code
    style: Regular
  italic:
    family: Fira Code
    style: Italic
  bold_italic:
    family: Fira Code
    style: Bold Italic
  size: 12.0
  offset:
    x: 0
    y: 0
  glyph_offset:
    x: 0
    y: 0

# Colors (SeaShells)
# Source : https://raw.githubusercontent.com/mbadolato/iTerm2-Color-Schemes/master/schemes/SeaShells.itermcolors
colors:
  # Default colors
  primary:
    background: '#18272b'
    foreground: '#e5c49e'

  # Colors the cursor will use if `custom_cursor_colors` is true
  cursor:
    text: '#061822'
    cursor: '#feaf3c'

  selection:
    text: '#ffe9d7'
    background: '#265b75'

  # Normal colors
  normal:
    black: '#1d485f'
    red: '#db662d'
    green: '#008eab'
    yellow: '#feaf3c'
    blue: '#255a62'
    magenta: '#77dbf4'
    cyan: '#5fb1c2'
    white: '#e5c49e'

  # Bright colors
  bright:
    black: '#545d65'
    red: '#dd998a'
    green: '#739da8'
    yellow: '#fedaae'
    blue: '#0bc7e3'
    magenta: '#c6e8f1'
    cyan: '#97b9c0'
    white: '#ffe9d7'


background_opacity: 0.80

selection:
  save_to_clipboard: true

cursor:
  style:
    shape: Block
  unfocused_hollow: true

live_config_reload: true

key_bindings:
  - { key: N,       mods: Control|Shift,           action: SpawnNewInstance }
