#! /bin/sh

# Autostart
pgrep -x sxhkd > /dev/null || sxhkd &
feh -z --bg-scale ~/stuffs/wallpaper &
# pkill picom &
picom --experimental-backends --config ~/.config/picom/picom.conf &
~/.config/polybar/launch.sh & 
dunst &
xset r rate 250 50 

# for desktop in $(bspc query -D); do 
#   feh -z --bg-fill ~/stuffs/wallpaper
# done

# desktop_ids = `bspc query -D`.split
# for id in desktop_ids; do 
#   feh -z --bg-fill ~/stuffs/wallpaper
# done


# if [[ $(xrandr -q | grep 'HDMI1 connected') ]]; then
#   xrandr --output HDMI1 --mode 1920x1080i --above eDP1
#   bspc monitor eDP1  -d  1 2 3 4 5
#   bspc monitor HDMI1 -d  6 7 8 9 10 
#   bspc monitor eDP1 -s HDMI1
# else
  bspc monitor -d 1 2 3 4 5 6 7 8 9 10
# fi


bspc config window_gap           5

bspc config split_ratio          0.52
bspc config top_padding          30

bspc config borderless_monocle   true
bspc config gapless_monocle      true

# bspc rule -a Gimp desktop='^8' state=floating follow=on
# bspc rule -a Chromium desktop='^2'
# bspc rule -a mplayer2 state=floating
# bspc rule -a Kupfer.py focus=on
# bspc rule -a Screenkey manage=off
bspc rule -a Slack desktop='^1' state=floating 
bspc rule -a discord desktop='^2' state=floating 


